### ISSUE TITLE
Best practices to include in an APEX app

### ISSUE THREAD

**Issue by devdogde** [ogobrecht/console#16]
Hello Ottmar,
I was wondering if you have some best practices to include console into an APEX app, especially:

- Report on console_logs (I have some issues displaying markdown tables correct)
- Change log level within the APEX app
- ...
Thanks for providing this awesome tool!
Florian

**Comment by ogobrecht** [comment]
Hi Florian,

sorry for my very late answer.

I checked it in the classic and interactive reports with Richtext/Markdown settings and I have to say you are right. It seems, that the native APEX Markdown renderer does (currently) not support Markdown tables.

You can workaround this with my [Markdown plug-in](https://github.com/ogobrecht/markdown-apex-plugin).

Please make sure you disable the sanitizer (otherwise for some reasons the level 4 and 5 headers are not rendered) and enable the Markdown Extra functionality (for tables and other things) during the plug-in installtion. You can configure this at any time under "Shared Components > Component Settings > Markdown [Plug-In]".

After the installation you simply create a dynamic action for the refresh of your report region:

- Right click the report in Page Designer and choose "Create Dynamic Action"
- As Action select "Markdown [Plug-In]"
- Make sure you check the "Fire on initialization" option

Please keep me informed and close this issue, if this works for you.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Florian,

as I have not received any new messages from you for a long time, I assume your question is answered. I will close now the issue. Feel free to reopen it, if you have any further question.

Best regards
Ottmar
